### ISSUE TITLE
Scope second model for inclusion in package

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#190]
I think that it would be beneficial for us to start thinking about including another model in the package beyond `latent_individual`. Aside from providing additional functionality, I think it'd be good sooner rather than later to test how our design decisions hold up to a new model.

Delay distribution connoisseur @zsusswein mentioned his interest in a delay-level model rather than individual-level model. I think something along these lines would be a good candidate. Reasoning: we have a slow but correct/good model, let's include a fast but less correct/good model. Naturally I think then we could perform some comparisons.

@seabbs @kgostic @parksw3 what are your opinions about this? Is there a model from the paper (and paper code) that you think would be best to have a go at reimplementing with our current infrastructure? Let me know and I can have a go.

**Comment by seabbs** [comment]
> Delay distribution connoisseur @zsusswein mentioned his interest in a delay-level model rather than individual-level model. I think something along these lines would be a good candidate. Reasoning: we have a slow but correct/good model, let's include a fast but less correct/good model. Naturally I think then we could perform some comparisons.

I'm strongly opposed to doing this as part of 0.1.0 or indeed anything other than its own work package. For the reason that it: 

1. Will be quite a bit of work
2. Requires validation/science
3. Has lots of choices that need to be discussed. 

I agree that a early stage additional model would be helpful here. I think we could proposed a few things here. 

1. Use a naive direct pass through to `brms`.  We originally discounted this as duplicating functionality available elsewhere and because we would never recommend users make use of it. However I now think this was a mistake because: 

- @athowes has needed to run default `brms` models to test understanding of different families and them being available in a different interface has drastically slowed this down. 
- I think this makes it much easier for users to check for themselves if the methods in this package are "worthwhile". Since we previously talked about this I have moved to think this is more important.
- For both our development work and for users being able to see how the default brms model works within the package should be a helpful education about how all the other models work (i.e without all of their other complexity). This feels like it would be very useful for us right now and of lesser but still use to users on an ongoing basis.

**Comment by athowes** [comment]
* Could just tell users to use `brms`
* But if they fit with us then they can do pre- and post- processing (and maybe better priors than `brms`)

**Comment by seabbs** [comment]
I think we can close this in favour of more specific issues for new models
