### ISSUE TITLE
Add common functions to namespace

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#341]
> the common CLI functions are good examples of things we might want in the namespace as we use them a lot

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/pull/329#discussion_r1765008164_

Also could do this for `checkmate` functions and anything else which seems appropriate.

Am I right in thinking never to use `@importFrom` in the roxygen next to the function and always centralised?

**Comment by seabbs** [comment]
> Am I right in thinking never to use @importFrom in the roxygen next to the function and always centralised?

I think if we are importing something because it is used a lot in one function that could be a good arg for doing it next to the function but if its because we use it several times across functions it might be clearer to centralise. I don't think it makes much different as you can just look at the namespace so whatever you would rather and can keep track of
