### ISSUE TITLE
Polish getting started vignette

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#57]
Good that we merged in the "get started" vignette and now can see it rendered: http://epidist.epinowcast.org/articles/epidist.html

There are a few small issues I can see with it that require polishing up:

* [x] Move loading packages to where the loading packages is mentioned
* [ ] Alter the "Finally, in Section [??](http://epidist.epinowcast.org/articles/epidist.html#compare), we demonstrate that the fitted delay distribution accurately recovers the underlying truth." (I merged two sections)
* [ ] Ideally the Table 2.1 caption should be altered to work like figure captions rather than this strange thing. I feel like this is possible but requires trying a few things out. Basically I'd like to be using `(ref:...)`
* [ ] The section at the end still has "Figure [2.2](http://epidist.epinowcast.org/articles/epidist.html#fig:fitted-lognormal) shows…" and an empty figure caption that need to be filled out

Can make a quick PR to fix these things tomorrow.

**Comment by parksw3** [comment]
This looks amazing. Just a few thoughts.

1. I wonder if we should define what we mean by primary vs secondary event? Or maybe it's obvious?

2. Should we add more citations or is Park & Charniga et al good enough? 

3. We might want to explain figure 1.4 a bit more carefully. I was slightly confused about how different delay times can have the same censored delay time. For example, if we have `ptime=0` and `stime=1.5`, then the observed delay is 1 day. But if `ptime=0.9` and `stime=2.4` then the observed delay is 2 days. Something about censoring happening at the event level, rather than at the delay level...

4. Figure 2.1: Just so I know I'm understanding this properly, do the orange bars represent full data without censoring? I wonder if it makes more sense to plot them with density plots (alongside the true density) since they're continuous data? We could also consider plotting something like the mean (vertical line) to show the bias.

**Comment by seabbs** [comment]
> I wonder if we should define what we mean by primary vs secondary event? Or maybe it's obvious?

Agree

>  Park & Charniga et al good enough?

I feel like its enough as an entry point (we could even say this explicitly?)

> if it makes more sense to plot them with density plots (alongside the true density) since they're continuous data? 

Agree
