### ISSUE TITLE
Automate updating documentation

### ISSUE THREAD

**Issue by athowes** [epinowcast/epidist#87]
The `.Rd` documentation is out-of-date. Is the correct workflow here that I should be calling `document()` before I merge things? That seems fine to me. For some reason, I had in some ways been thinking of the `.Rd` as being generated along with the website so that I don't have to keep this up-to-date myself, but perhaps that isn't the case. Is there an easy to way to move to that?

**Comment by seabbs** [comment]
So yes that is the current workflow (and the workflow most packages use) you can automate with pre commit if you wish. 

However, I agree it makes a lot more sense for this to be done in CI in most cases. I like the idea of doing this like we handle the readme but you would need to do it so it pushes to a PR (as R CMD check fails when documentation is out of date). We currently have a PR command so that a /document comment in a epinowcast PR should trigger a redoc (so this would be a more automated but not fully automated version). 

The above points out something we need sooner rather than later to make dev easier - passing R cmd check so we can start properly using our CI vs ignoring it (as it catches all of these kinds of issues by design)

**Comment by athowes** [comment]
Yes good point about passing `R CMD CHECK` (#14). Will reup that mentally.

**Comment by athowes** [comment]
Perhaps this issue shouldn't be closed by #88 and instead we should keep it open and decide on how to do this going foward. I'm not that familiar with the options (haven't used precommits before, not that familiar with the bots). Can come to an opinion at some point.
